(function(r,f){const a=f(typeof module==='object'&&module.exports?require('./music-titles.js'):r.StarMusicTitles);if(typeof module==='object'&&module.exports)module.exports=a;else r.StarCareer=a;})(typeof globalThis!=='undefined'?globalThis:this,function(MUSIC){
'use strict';
const CONFIG={checkMs:300000,newMs:600000,returnChance:.35,raise:.1,maxRaise:.5,ideaMs:600000,ideaChance:.15,ideaFee:300};
const POOLS={music:[['未寄出的晴天','把未說出口的心意唱成一封信。'],['沿海慢車','以輕快節奏收集旅途中的相遇。'],['一盞晚安','陪伴城市深夜歸人的溫柔單曲。'],['轉角的回聲','從日常小聲音尋找新的旋律。'],['口袋裡的夏天','把難忘的夏日整理成一首歌。']],drama:[['四樓的燈','老公寓裡，陌生鄰居開始互相照顧。'],['明天再見','兩位朋友在重逢後練習坦白。'],['午後小店','一間小店串起街坊的日常故事。'],['候車月台','錯過的班車帶來意外相遇。']],movie:[['雨停以前','一場雨讓疏遠的家人重新對話。'],['遠方的留言','循著一段錄音，踏上返鄉旅程。'],['無聲合奏','兩個性格不同的人學會互相傾聽。'],['最後一班日光','在城市邊緣找回被遺忘的夢。']],brand:[['漫日生活季','以自然形象傳遞日常生活的美感。'],['微光選品季','讓簡單物件帶來溫暖陪伴。'],['原色日常季','用真誠故事介紹自在生活。']]};
const DEFINITIONS=[{key:'lead',pool:'movie',label:'電影主演',pay:3200,fame:45,fatigue:25,skill:'act',min:80,fameMin:90,duration:5},{key:'contract',pool:'brand',label:'季度品牌長約',pay:5200,fame:65,fatigue:30,skill:'poise',min:100,fameMin:240,duration:5},{key:'record_pay',pool:'music',label:'唱片指名 · 實力製作',pay:3600,fame:30,fatigue:23,skill:'sing',min:180,fameMin:180,duration:5,record:true,exposure:1},{key:'record_buzz',pool:'music',label:'唱片指名 · 話題新聲',pay:1800,fame:40,fatigue:23,skill:'sing',min:100,fameMin:140,duration:5,record:true,exposure:1.6}];
const copy=x=>JSON.parse(JSON.stringify(x));
function init(s){s.career={rng:((s.rng||1)^0x73a11)>>>0,serial:0,names:{},checks:{},offers:[],ideas:[]};}
function random(s){const c=s.career;c.rng=(Math.imul(c.rng,1664525)+1013904223)>>>0;return c.rng/4294967296;}
function name(s,pool){const c=s.career,i=c.names[pool]||0,p=POOLS[pool];c.names[pool]=i+1;const row=p[i%p.length];return {title:row[0],desc:row[1],instance:'work-'+(++c.serial)};}
function eligible(a,e){return !!a?.debuted&&a.fame>=e.fameMin&&a[e.skill]>=e.min&&a.confidence>=40;}
function migrate(s){init(s);s.events=s.events.map(e=>{const d=DEFINITIONS.find(d=>d.key===e.id),a=s.artists.find(a=>eligible(a,d))||s.artists[0];if(!a)return e;const n={...e,kindId:d.key,artistId:a.id,artistName:a.name,fameMin:d.fameMin,skill:d.skill,min:d.min,status:'pending',basePay:e.pay,attempts:0,nextAt:0,legacy:true};s.career.offers.push(copy(n));return n;}).filter(Boolean);}
function check(s,at,offline=false){if(offline)return;const c=s.career;
 for(const e of s.events.filter(e=>!e.artistId)){const d=DEFINITIONS.find(d=>d.key===e.id),a=s.artists.find(a=>eligible(a,d));if(a){Object.assign(e,{kindId:d.key,artistId:a.id,artistName:a.name,fameMin:d.fameMin,min:d.min,skill:d.skill,status:'pending',basePay:e.pay,attempts:0,nextAt:0,legacy:true});c.offers.push(copy(e));}}
 for(const o of c.offers.filter(o=>o.status==='cooldown'&&at>=o.nextAt)){o.nextAt=at+CONFIG.checkMs;const a=s.artists.find(a=>a.id===o.artistId);if(!eligible(a,o))continue;if(random(s)<CONFIG.returnChance){o.attempts++;o.pay=Math.round(o.basePay*(1+Math.min(CONFIG.maxRaise,o.attempts*CONFIG.raise)));o.status='pending';s.events.push(copy(o));}}
 for(const a of s.artists){for(const d of DEFINITIONS){const key=a.id+':'+d.key;if(c.offers.some(o=>o.artistId===a.id&&o.kindId===d.key&&['pending','cooldown','active'].includes(o.status)))continue;if(at<(c.checks[key]||s.startedAt+CONFIG.checkMs))continue;c.checks[key]=at+CONFIG.checkMs;if(!eligible(a,d)||random(s)>=.35)continue;const ref=d.record?MUSIC.invitation(s):null,n=ref?{title:ref.title,desc:'借用原始音樂作品名，在星序作為單曲指名企劃；原作單曲／專輯分類未確認。',instance:ref.id}:name(s,d.pool),o={...d,id:'invite-'+(++c.serial),kindId:d.key,title:n.title,desc:n.desc,workInstance:n.instance,...(ref?{titleRef:ref}:{}),artistId:a.id,artistName:a.name,appeared:at,status:'pending',basePay:d.pay,attempts:0,nextAt:0};c.offers.push(o);s.events.push(copy(o));}
 const key=a.id+':idea';if(!a.debuted||c.ideas.some(i=>i.artistId===a.id&&!['done','shelved','withdrawn'].includes(i.status))||at<(c.checks[key]||s.startedAt+CONFIG.ideaMs))continue;c.checks[key]=at+CONFIG.ideaMs;if(random(s)>=CONFIG.ideaChance)continue;const n=name(s,'music');c.ideas.push({...n,id:'idea-'+(++c.serial),artistId:a.id,artistName:a.name,status:'pending',progress:0,revisions:0,fee:CONFIG.ideaFee,createdAt:at});}
}
function declined(s,e){const o=s.career.offers.find(o=>o.id===e.id);if(!o)return;o.status='cooldown';o.nextAt=s.lastTick+CONFIG.checkMs;}
function accepted(s,e){const o=s.career.offers.find(o=>o.id===e.id);if(o)o.status='active';}
function finished(s,id,at){const o=s.career.offers.find(o=>o.id===id);if(o){o.status='completed';o.completedAt=at;s.career.checks[o.artistId+':'+o.kindId]=at+CONFIG.newMs;}const idea=s.career.ideas.find(i=>i.id===id);if(idea){idea.status='done';idea.completedAt=at;s.career.checks[idea.artistId+':idea']=at+CONFIG.ideaMs;}}
function canceled(s,id){const o=s.career.offers.find(o=>o.id===id)||s.career.ideas.find(i=>i.id===id);if(o){o.status='withdrawn';s.career.checks[o.artistId+':'+(o.kindId||'idea')]=s.lastTick+CONFIG.newMs;}}
function release(s,id){for(const o of [...s.career.offers,...s.career.ideas])if(o.artistId===id&&!['completed','done','shelved','withdrawn'].includes(o.status))o.status='withdrawn';s.events=s.events.filter(e=>e.artistId!==id);}
function ideaChoice(s,id,choice){const i=s.career.ideas.find(i=>i.id===id),a=s.artists.find(a=>a.id===i?.artistId);if(!i||!a||!['pending','revision'].includes(i.status))return {ok:false,reason:'企劃已處理或藝人不在公司。'};if(i.status==='revision'&&s.lastTick<i.reviewAt)return {ok:false,reason:'正在修改構想，請稍後回來。'};if(choice==='shelve'){i.status='shelved';s.career.checks[a.id+':idea']=s.lastTick+CONFIG.ideaMs;return {ok:true};}if(choice==='revise'){if(i.revisions>=2)return {ok:false,reason:'已修改兩次，可支持或擱置。'};i.revisions++;i.status='revision';i.reviewAt=s.lastTick+30000;return {ok:true};}if(choice!=='support')return {ok:false,reason:'選項不存在。'};if(a.task||a.project)return {ok:false,reason:'請先完成目前活動與長案。'};if(s.cash<i.fee)return {ok:false,reason:'資金不足，需要創作準備費 $'+i.fee};s.cash-=i.fee;i.status='preparing';i.paid=i.fee;return {ok:true};}
function titleValue(i,value){if(typeof value!=='string'||/[\u0000-\u001f\u007f-\u009f]/u.test(value))return {ok:false,reason:'歌名不可包含控制字元。'};const title=value.trim()||(i.suggestedTitle||i.title);if([...title].length>40)return {ok:false,reason:'歌名最多40個字。'};return {ok:true,title};}
function renameIdea(s,id,value){const i=s.career.ideas.find(i=>i.id===id);if(!i||!['pending','revision','preparing','ready'].includes(i.status))return {ok:false,reason:'製作開始後歌名已鎖定。'};const r=titleValue(i,value);if(!r.ok)return r;i.suggestedTitle??=i.title;i.title=r.title;return r;}
function prepare(s,a,id){const i=s.career.ideas.find(i=>i.id===id&&i.artistId===a.id&&i.status==='preparing');if(!i)return null;const units=10+Math.floor((a.intellect+a.speech)/100);i.progress=Math.min(100,i.progress+units);if(i.progress===100){i.status='ready';i.qualityBonus=Math.min(15,Math.round((a.intellect+a.speech)/1998*10)+i.revisions*2);}return i;}
function validate(s,people){const c=s.career,num=n=>Number.isSafeInteger(n)&&n>=0;if(!c||!num(c.rng)||c.rng>4294967295||!num(c.serial)||!c.names||!Object.entries(c.names).every(([k,v])=>POOLS[k]&&num(v))||!c.checks||!Object.values(c.checks).every(v=>Number.isFinite(v)&&v>=0)||!Array.isArray(c.offers)||!Array.isArray(c.ideas))throw Error('企劃存檔損壞');const ids=new Set();for(const o of [...c.offers,...c.ideas]){if(!o||typeof o.id!=='string'||!(/^(invite|idea)-[1-9][0-9]*$/.test(o.id)||['lead','contract'].includes(o.id))||ids.has(o.id)||!people.some(a=>a.id===o.artistId)||typeof o.title!=='string'||typeof o.desc!=='string'||!['pending','cooldown','active','completed','withdrawn','revision','preparing','ready','producing','done','shelved'].includes(o.status))throw Error('企劃紀錄損壞');ids.add(o.id);}for(const o of c.offers)if(!DEFINITIONS.some(d=>d.key===o.kindId)||!num(o.pay)||o.pay>10000||!num(o.basePay)||o.basePay>10000||!num(o.attempts)||!Number.isFinite(o.nextAt)||o.nextAt<0)throw Error('邀約條件損壞');for(const i of c.ideas)if((i.suggestedTitle!==undefined&&(typeof i.suggestedTitle!=='string'||!i.suggestedTitle.trim()||!titleValue(i,i.title).ok))||!num(i.progress)||i.progress>100||!num(i.revisions)||i.revisions>2||i.fee!==CONFIG.ideaFee)throw Error('原創企劃進度損壞');}
return {MUSIC,CONFIG,POOLS,DEFINITIONS,init,migrate,name,eligible,check,declined,accepted,finished,canceled,release,ideaChoice,titleValue,renameIdea,prepare,validate};
});
