(()=>{const G=StarGame,esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const drafts=new Map();let draftOwner=null;
document.addEventListener('input',e=>{if(e.target.matches('[data-original-title]'))drafts.set(e.target.dataset.originalTitle,e.target.value);});
function nameField(i){if(!['pending','revision','preparing','ready'].includes(i.status))return '';return `<label class="original-name-field">歌曲名稱<input data-original-title="${esc(i.id)}" value="${esc(drafts.get(i.id)??i.title)}" placeholder="${esc(i.suggestedTitle||i.title)}" aria-label="${esc(i.artistName)}的歌曲名稱"><small>最多40字；空白使用建議名。開始錄製後鎖定。</small></label><button data-original-name-save="${esc(i.id)}">儲存歌名</button>`;}
function eventCard(s,e){const a=s.artists.find(a=>a.id===e.artistId),q=G.canDecide(s,e.id,e.artistId);return `<article class="event"><small>${esc(e.label||'重要邀約')} · ${e.record?'長案 · 4日':'5秒活動'}</small><h3>《${esc(e.title)}》</h3><p class="booking-assignee">指名 <b>${esc(e.artistName)}</b> · 不可轉派</p><div class="requirement">條件：${StarQualificationUI.invitation(s,e)}</div><div class="offer-details"><strong>報酬 ${StarMoney.format(G.payout(a,{...e,kind:'special'}))}</strong><span>費用：${e.record?'管理約 '+StarMoney.format(Math.ceil(G.JOBS.find(j=>j.id==='radio').duration/60*G.SALARY_RATE)):'親自安排無費用'}</span></div><p class="booking-condition ${q.ok?'':'locked'}">${esc(q.reason||'符合資格，可接受指名邀約。')}</p><input type="hidden" id="event-${e.id}" value="${e.artistId}"><button class="primary" data-accept="${e.id}" ${q.ok?'':'disabled'}>接受指名邀約</button><button data-decline="${e.id}">婉拒，等待可能重邀</button><details class="job-rules"><summary>工作說明與結算規則</summary><p>${esc(StarDisplayCopy.description(e.desc))}</p><p>本次基礎 ${e.pay}（原價 ${e.basePay}）。${e.record?`4遊戲天製作，完成後7天熱度；${e.exposure>1?'曝光型播放預算為同品質普通單曲的1.6倍，粉絲依實際播放轉換。':'實力型採正常作品曝光與轉換。'}接受即啟用長案管理，公司共用30/分鐘，可暫停改親自製作。`:'收益依既有藝人條件調整。'}</p></details></article>`;}
function render(s,company=null){if(draftOwner!==s.career){drafts.clear();draftOwner=s.career;}const movie=company==='global';if(movie)s={...s,events:s.events.filter(e=>StarCompanyRoutes.invitationCompany(e)==='global'),career:{...s.career,offers:s.career.offers.filter(e=>StarCompanyRoutes.invitationCompany(e)==='global'),completedWorks:(s.career.completedWorks||[]).filter(w=>w.kind==='movie')}};const host=document.getElementById('opportunities');host.hidden=false;
host.innerHTML=`<h3>${movie?'遠映影業 · 電影主演邀約':'指名邀約與原創企劃'}</h3>${movie?'<p>一般電影通告尚未開放。下列為現有的5秒電影主演指名邀約，必須由經紀人親自回覆。</p>':''}<details class="job-rules"><summary>邀約與重邀規則</summary><p>依各藝人的個人名氣、相關能力與出道資格判定，不看公司名氣合計。達標後每5分鐘一次35%機會；只有完成工作才判定，離線不代接。婉拒後每5分鐘35%機率重邀同名同人，每次回邀基礎價加10%，最多50%；完成後至少10分鐘才有新案。</p></details><details><summary>查看初版資格與報酬</summary>${G.CAREER.DEFINITIONS.filter(d=>!movie||d.key==='lead').map(d=>`<p>${esc(d.label)}：已出道、個人名氣${d.fameMin}、${G.SKILLS[d.skill]}${d.min}、自信40；基礎 $${d.pay}${d.record?' · 四天製作，七天熱度':' · 5秒'}。</p>`).join('')}</details>
${s.events.map(e=>eventCard(s,e)).join('')||'<p>目前沒有待回覆邀約。達標藝人持續工作時有機會收到。</p>'}
${s.career.offers.filter(e=>e.status==='cooldown').map(e=>`<p class="muted">《${esc(e.title)}》 · ${esc(e.artistName)} · 同案重邀最早還有 ${Math.max(0,Math.ceil((e.nextAt-s.lastTick)/1000))} 秒；之後35%機率判定。</p>`).join('')}
<div ${movie?'hidden':''}><h3>藝人想寫的歌</h3><p>完成音樂第一章會直接保留可命名企劃，不用等隨機構想。其他構想維持原機率，助理不會決定。支持費 $300；修改免費、每次30秒，最多兩次。準備每段5秒，進度＝10＋⌊（才智＋口才）÷100⌋，累積100後可錄製。準備品質加成最多15點；歌藝仍影響演唱品質。</p>
${s.career.ideas.filter(i=>!['done','shelved','withdrawn'].includes(i.status)).map(i=>`<article class="event"><h3>${esc(i.artistName)}：想寫《${esc(i.title)}》</h3><p>${esc(i.desc)}</p>${nameField(i)}<p>${esc({pending:'等待你的想法',revision:'修改構想中',preparing:'寫詞／作曲準備',ready:'準備完成，可開始錄製',producing:'四天單曲製作中'}[i.status])} · ${i.progress}/100 · 已修改${i.revisions}次</p>${['pending','revision'].includes(i.status)?`<p>支持即付 $${i.fee}；錄製完成採一般單曲基礎 $760，之後七天熱度。</p><button data-idea="${i.id}" data-idea-choice="support" ${s.cash<i.fee?'disabled':''}>支持企劃 · $${i.fee}</button><button data-idea="${i.id}" data-idea-choice="revise" ${i.revisions>=2?'disabled':''}>先修改 · 免費30秒</button><button data-idea="${i.id}" data-idea-choice="shelve">擱置</button>`:i.status==='preparing'?`<button data-compose="${i.id}" data-composer="${i.artistId}">親自安排創作 · 5秒</button>`:i.status==='ready'?`<p>創作準備品質 +${i.qualityBonus}，製作設備另計；總品質上限100。</p><button data-original-launch="${i.id}">開始4天錄製並啟用長案管理</button>`:''}</article>`).join('')||'<p>目前沒有新的原創歌曲構想。</p>'}
</div><section class="music-history" ${movie?'hidden':''}><h3>音樂工作履歷</h3>${s.career.ideas.filter(i=>i.status==='done').slice(-20).reverse().map(i=>`<p>《${esc(i.title)}》 · ${esc(i.artistName)} · 原創單曲</p>`).join('')}${(s.musicTitles?.history||[]).slice(-20).reverse().map(w=>`<p>《${esc(StarDisplayCopy.workTitle(w))}》 · ${esc(w.artistName)} · ${w.kind==='cafe'?'音樂短通告':'單曲'} · 實收 $${w.earned}</p>`).join('')||'<p>新接正式音樂長案完成後，作品名稱與藝人會留在這裡。短通告不具歌曲名，也不加入唱片熱度。</p>'}</section><h3>已完成的重要活動</h3>${(s.career.completedWorks||[]).slice().reverse().map(w=>`<p>《${esc(StarDisplayCopy.workTitle(w))}》 · ${esc(w.artistName)} · ${w.kind==='movie'?'電影':'品牌'} · 實收 $${w.earned}<br>${esc(StarDisplayCopy.description(w.desc))}</p>`).join('')||'<p>完成的電影／品牌活動會保留獨立紀錄；歌曲與戲劇請看作品頁。</p>'}`;
}
window.StarCareerUI={render,clearDraft:id=>drafts.delete(id)};})();
