(function(r,f){const a=f();if(typeof module==='object'&&module.exports)module.exports=a;else r.StarCustomArtists=a;})(globalThis,function(){
 'use strict';
 const BASE=Object.freeze({act:18,sing:16,speech:18,poise:18,movement:17,stamina:18,intellect:18,confidence:18}),BUDGET=21,CAP=36;
 const PORTRAITS=Object.freeze(['male1','male2','male3','female1','female2','female3'].map((id,i)=>Object.freeze({id,gender:i<3?'male':'female',label:(i<3?'男':'女')+'性素人 '+(i%3+1),path:'assets/custom/'+id+'.png'})));
 const PERSONALITIES=Object.freeze({warm:{label:'親切健談',text:'喜歡和人交換想法，也正在練習把話說得清楚。',idle:'今天想聽聽大家的想法，再一起找個開始的地方。'},quiet:{label:'安靜細膩',text:'習慣先觀察與記錄，願意慢慢把感受說出來。',idle:'我先把想到的記下來，等一下再慢慢說。'},steady:{label:'踏實認真',text:'喜歡把練習拆成小步驟，一次做好一件事。',idle:'今天先把一件小事做好，慢慢累積就行。'}});
 function nameUnits(name){return [...name.trim().normalize('NFC')].reduce((n,c)=>n+(/\p{Mark}/u.test(c)?0:/[\x20-\x7e]/.test(c)||/\p{Script=Latin}/u.test(c)?1:2),0);}
 function nameError(name,legacy=false){if(typeof name!=='string'||!name.trim())return '請輸入藝人姓名。';if([...name.trim()].length>64)return '姓名最多64個字元，請自行調整；不會自動截斷。';if(!legacy&&nameUnits(name)>8)return '姓名超過8格：中文最多4字；英文與空格各1格，中文字各2格。';if(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/u.test(name))return '姓名不能包含控制字元或換行。';return null;}
 function normalizeName(name){return name.trim();}
 function allocation(stats){if(!stats||typeof stats!=='object'||Array.isArray(stats)||Object.keys(stats).length!==8||!Object.entries(BASE).every(([k,b])=>Number.isInteger(stats[k])&&stats[k]>=b&&stats[k]<=CAP))return {ok:false,reason:'能力須為基礎至36之間的整數。'};const used=Object.entries(BASE).reduce((n,[k,b])=>n+stats[k]-b,0);return {ok:used<=BUDGET,used,remaining:Math.max(0,BUDGET-used),reason:used>BUDGET?'已超出21點配點額度。':null};}
 function allocate(stats,key,value){const a=allocation(stats);if(!a.ok||!Object.hasOwn(BASE,key)||!Number.isInteger(value)||value<BASE[key])return {ok:false};const next=Math.min(value,CAP,stats[key]+a.remaining);return {ok:true,stats:{...stats,[key]:next}};}
 function inspect(d,legacyName=false){if(!d||typeof d!=='object')return {ok:false,reason:'建角資料不完整。'};const e=nameError(d.name,legacyName);if(e)return {ok:false,reason:e};if(!PORTRAITS.some(p=>p.id===d.portraitId)||!Object.hasOwn(PERSONALITIES,d.personalityId))return {ok:false,reason:'請選擇肖像與個性。'};const a=allocation(d.stats);if(!a.ok)return a;if(a.remaining)return {ok:false,reason:`還有 ${a.remaining} 點尚未分配。`,remaining:a.remaining};return {ok:true,name:normalizeName(d.name),stats:{...d.stats}};}
 function specialty(stats){return Object.entries({act:'drama',sing:'music',poise:'ad'}).find(([k])=>Number.isInteger(stats?.[k])&&stats[k]>=30)?.[1]||null;}
 function specialtyText(stats){const type=specialty(stats);return type?({drama:'戲劇',music:'音樂',ad:'廣告'}[type]+'通告報酬＋15%（依初始配點固定）'):'尚無報酬專長（演技／歌藝／儀態任一達30可獲對應＋15%）';}
 function definition(record){const p=PORTRAITS.find(p=>p.id===record.portraitId),c=PERSONALITIES[record.personalityId];return {id:record.id,name:record.name,...record.stats,fame:0,origin:'custom',role:'自創素人',tag:c.label,trait:c.text+' '+specialtyText(record.stats)+'；個性與肖像不提供能力加成。',bonusType:specialty(record.stats),color:'mint',portrait:p.path,sdPortrait:p.path,portraitStatus:'已批准原創2D立繪',sdStatus:'自創靜態形象',uncertainFields:[],personalityId:record.personalityId,portraitId:record.portraitId};}
 function people(s){return (s.customRegistry||[]).map(definition);}
 function validate(s){if(!Array.isArray(s.customRegistry)||!Number.isSafeInteger(s.customSerial)||s.customSerial<0)throw Error('自創藝人登錄資料損壞');const ids=new Set();for(const r of s.customRegistry){if(!r||!/^custom_[1-9][0-9]*$/.test(r.id)||Number(r.id.slice(7))>s.customSerial||ids.has(r.id)||!inspect(r,true).ok||r.name!==normalizeName(r.name))throw Error('自創藝人身份或初始配點損壞');ids.add(r.id);}}
 return {allocation,allocate,nameUnits,nameError,specialty,specialtyText,BASE,BUDGET,CAP,PORTRAITS,PERSONALITIES,inspect,definition,people,validate};
});
