(()=>{
 'use strict';const G=StarGame,C=G.CUSTOM,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dialog=document.createElement('dialog');dialog.id='custom-artist-dialog';dialog.setAttribute('aria-labelledby','custom-title');document.body.append(dialog);let api=null,draft=null,review=false,opener=null,lastPortrait=null,composing=false;
 function close(){dialog.close();draft=null;review=false;opener?.focus({preventScroll:true});}
 function ready(){const p=dialog.querySelector(`[data-custom-image="${draft.portraitId}"]`);return !!p?.complete&&p.naturalWidth>0;}
 function renderPortrait(){const gender=draft.portraitId.startsWith('female')?'female':'male',list=C.PORTRAITS.filter(p=>p.id.startsWith(gender)),index=list.findIndex(p=>p.id===draft.portraitId),p=list[index];dialog.querySelector('#custom-carousel').innerHTML=`<label>性別<select id="custom-gender"><option value="male" ${gender==='male'?'selected':''}>男性</option><option value="female" ${gender==='female'?'selected':''}>女性</option></select></label><div class="custom-portrait-stage"><button type="button" data-custom-step="-1" aria-label="上一款肖像">‹</button><img data-custom-image="${p.id}" src="${p.path}" alt="${p.label}，完整半身預覽"><button type="button" data-custom-step="1" aria-label="下一款肖像">›</button></div><p class="custom-portrait-caption" aria-live="polite">${p.label} · ${index+1}/3 款</p>`;const img=dialog.querySelector('[data-custom-image]');img.addEventListener('load',update);img.addEventListener('error',update);}
 function cycle(delta){read();const gender=draft.portraitId.startsWith('female')?'female':'male',list=C.PORTRAITS.filter(p=>p.id.startsWith(gender)),index=list.findIndex(p=>p.id===draft.portraitId);draft.portraitId=list[(index+delta+list.length)%list.length].id;lastPortrait[gender]=draft.portraitId;renderPortrait();update();dialog.querySelector(`[data-custom-step="${delta}"]`).focus({preventScroll:true});}
 function read(){draft.name=dialog.querySelector('#custom-name').value;draft.personalityId=dialog.querySelector('#custom-personality').value;for(const k of Object.keys(C.BASE)){const input=dialog.querySelector(`[data-custom-stat=${k}]`),n=input.value===''?NaN:Number(input.value),result=C.allocate(draft.stats,k,n);input.setCustomValidity(result.ok?'':'請輸入不低於基礎值的整數。');input.setAttribute('aria-invalid',String(!result.ok));if(result.ok){draft.stats=result.stats;input.value=draft.stats[k];}}}
 function invalid(){return [...dialog.querySelectorAll('[data-custom-stat]')].some(i=>i.getAttribute('aria-invalid')==='true');}
 function adjust(key,delta){read();const result=C.allocate(draft.stats,key,draft.stats[key]+delta);if(result.ok){draft.stats=result.stats;const input=dialog.querySelector(`[data-custom-stat=${key}]`);input.value=draft.stats[key];}update();}
 function controls(){const a=C.allocation(draft.stats);for(const k of Object.keys(C.BASE)){const input=dialog.querySelector(`[data-custom-stat=${k}]`);input.max=Math.min(C.CAP,draft.stats[k]+a.remaining);dialog.querySelector(`[data-custom-add=${k}]`).disabled=a.remaining===0||draft.stats[k]>=C.CAP;dialog.querySelector(`[data-custom-sub=${k}]`).disabled=draft.stats[k]<=C.BASE[k];}}
 function update(){if(review||!draft||!dialog.querySelector('#custom-form'))return;read();controls();const candidate={...draft.stats,fame:0,debuted:false},valid=Object.entries(C.BASE).every(([k,b])=>Number.isInteger(draft.stats[k])&&draft.stats[k]>=b&&draft.stats[k]<=C.CAP),eligible=valid?G.JOBS.filter(j=>!j.productionDays&&!G.jobLocks(candidate,j).length).map(j=>j.name):[];dialog.querySelector('#custom-specialty').textContent='初始專長：'+C.specialtyText(draft.stats)+'；確認簽約後固定，後天訓練不解鎖或改換。';dialog.querySelector('#custom-eligible').textContent='目前配點可接入門通告：'+(valid?(eligible.join('、')||'尚無符合，可調整能力。'):'請先將各項能力填在有效範圍。');const used=Object.entries(C.BASE).reduce((n,[k,b])=>n+draft.stats[k]-b,0),q=G.customQuote(api.state(),draft),host=dialog.querySelector('#custom-live');host.textContent=`已分配 ${used}/21 點 · 剩餘 ${21-used} 點 · 名氣固定0。${invalid()?'請修正標示的能力數值，才能預覽簽約。':q.reason||'配點完成，可預覽簽約。'}`;dialog.querySelector('#custom-preview').disabled=!q.ok||!ready()||invalid();dialog.querySelector('#custom-portrait-status').textContent=ready()?'肖像已就緒；外觀不影響能力。':'選定肖像尚未載入，請稍候；不會以缺圖狀態簽約。';}
 function render(){dialog.innerHTML=`<header><div><small>CREATE · 素人養成</small><h2 id="custom-title">自創藝人</h2></div><button type="button" data-custom-close aria-label="取消建角">✕</button></header><div id="custom-body"></div>`;const body=dialog.querySelector('#custom-body');
 if(review){const q=G.customQuote(api.state(),draft),quote=q.quote||G.signingQuote({...draft.stats,fame:0});body.innerHTML=`<section class="custom-review"><img src="${C.PORTRAITS.find(p=>p.id===draft.portraitId).path}" alt="選定肖像"><h3>${esc(draft.name.trim())}</h3><p>${esc(C.PERSONALITIES[draft.personalityId].label)} · 自創素人 · 名氣0</p><p>總能力162 · ${esc(C.specialtyText(draft.stats))}</p><dl>${Object.entries(G.SKILLS).map(([k,v])=>`<dt>${v}</dt><dd>${draft.stats[k]}</dd>`).join('')}</dl><h3>簽約金 $${quote.fee}</h3><p>${esc(quote.basis)}；無額外建角費。確認後才扣款並占用1個現有名額。</p><p>目前公司 ${api.state().artists.length}/${api.state().capacity} 人</p><p>可接入門工作：${q.eligible?.map(esc).join('、')||'目前尚無符合；加入後可安排訓練。'}</p><p id="custom-error" role="status">${esc(q.reason||'')}</p><button type="button" data-custom-back>返回調整</button><button type="button" id="custom-confirm" ${q.ok?'':'disabled'}>確認簽約 · $${quote.fee}</button></section>`;return;}
 body.innerHTML=`<form id="custom-form"><p>八能力基礎共141，另有21點自由分配；單項初始最多36。名氣從0開始，之後慢慢培養。</p><label>藝人姓名（中文最多4字／英文含空格最多8字元）<input id="custom-name" autocomplete="off" value="${esc(draft.name)}" placeholder="中文2格、英文與空格1格，共8格"></label><fieldset><legend>選擇成人素人肖像 · 3男3女</legend><div id="custom-carousel" role="group" aria-label="選擇肖像，左右鍵可切換同一性別款式"></div><p id="custom-portrait-status"></p></fieldset><label>個性（只影響文字，不改能力或報酬）<select id="custom-personality">${Object.entries(C.PERSONALITIES).map(([k,p])=>`<option value="${k}" ${k===draft.personalityId?'selected':''}>${p.label}</option>`).join('')}</select></label><div class="custom-stats">${Object.entries(G.SKILLS).map(([k,v])=>`<label>${v}<small>基礎 ${C.BASE[k]} · 上限36</small><span class="custom-stat-control"><button type="button" data-custom-sub="${k}" aria-label="減少${v}">−</button><input type="number" data-custom-stat="${k}" min="${C.BASE[k]}" max="36" step="1" value="${draft.stats[k]}" aria-label="${v}初始能力"><button type="button" data-custom-add="${k}" aria-label="增加${v}">＋</button></span></label>`).join('')}</div><p id="custom-specialty" role="status"></p><p id="custom-eligible" role="status"></p><p id="custom-live" role="status"></p><button type="button" data-custom-reset>重設配點</button><button type="submit" id="custom-preview">預覽簽約</button><button type="button" data-custom-close>取消，不建立藝人</button></form>`;
 renderPortrait();body.querySelectorAll('img').forEach(img=>{img.addEventListener('load',update);img.addEventListener('error',update);});update();}
 dialog.addEventListener('compositionstart',()=>{composing=true;dialog.querySelector('#custom-preview').disabled=true;});dialog.addEventListener('compositionend',()=>{composing=false;if(!review)update();});dialog.addEventListener('input',e=>{if(!review&&!composing&&!e.isComposing)update();});dialog.addEventListener('change',e=>{if(review)return;if(e.target.id==='custom-gender'){const gender=e.target.value;read();draft.portraitId=lastPortrait[gender];renderPortrait();update();dialog.querySelector('#custom-gender').focus({preventScroll:true});}else update();});
 dialog.addEventListener('keydown',e=>{if(!review&&e.target.matches('[data-custom-stat]')&&['ArrowUp','ArrowDown','PageUp','PageDown'].includes(e.key)){e.preventDefault();adjust(e.target.dataset.customStat,['ArrowUp','PageUp'].includes(e.key)?1:-1);return;}if(!review&&e.target.closest('.custom-portrait-stage')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();cycle(e.key==='ArrowLeft'?-1:1);}});
 dialog.addEventListener('submit',e=>{e.preventDefault();if(composing)return;update();if(!invalid()&&G.customQuote(api.state(),draft).ok&&ready()){review=true;render();dialog.scrollTop=0;}});
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.customAdd){adjust(b.dataset.customAdd,1);}else if(b.dataset.customSub){adjust(b.dataset.customSub,-1);}else if(b.hasAttribute('data-custom-close'))close();else if(b.dataset.customStep){cycle(Number(b.dataset.customStep));}else if(b.hasAttribute('data-custom-reset')){read();draft.stats={...C.BASE};render();}else if(b.hasAttribute('data-custom-back')){review=false;render();}else if(b.id==='custom-confirm'){b.disabled=true;const result=api.confirm(draft);if(result?.ok)close();else{dialog.querySelector('#custom-error').textContent=result?.reason||'未能簽約，請確認目前分頁仍可儲存。';b.disabled=false;}}});
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 window.StarCustomUI={open(ctx){api=ctx;composing=false;opener=document.activeElement;lastPortrait={male:'male2',female:'female1'};draft={name:'',portraitId:'male2',personalityId:'warm',stats:{...C.BASE}};review=false;render();dialog.showModal();dialog.querySelector('#custom-name').focus();}};
})();
