(function(r,f){const api=f();if(typeof module==='object'&&module.exports)module.exports=api;else r.StarMusicChapter=api;})(globalThis,function(){
'use strict';
const choices=[['music','explore'],['encourage','goal'],['steady','color'],['celebrate','listen','next'],['support','accumulate']];
function formal(s,id){return [...(s.works||[]),...(s.archivedWorks||[])].filter(w=>w.artistId===id&&w.kind==='music'&&w.jobId==='radio').sort((a,b)=>a.releasedAt-b.releasedAt||a.id-b.id);}
function get(s,id){return s.musicChapter?.artists?.[id];}
function init(s){for(const a of s.artists){if(!(s.customRegistry||[]).some(c=>c.id===a.id))continue;s.musicChapter??={version:1,artists:{},reader:null};if(!get(s,a.id)){const count=(s.log||[]).filter(l=>l.text.startsWith(a.name+'完成')&&l.text.includes('訓練，')).length;s.musicChapter.artists[a.id]={choices:[],training:count,started:false,pending:null};}}}
function scan(s){init(s);for(const a of s.artists){const h=get(s,a.id);if(!h)continue;const works=formal(s,a.id);if(a.project?.jobId==='radio'||works.length||s.musicTitles?.history?.some(w=>w.artistId===a.id&&w.kind==='radio'))h.started=true;const n=h.choices.length,ready=[true,a.sing>=40&&h.training>=3,a.sing>=80&&a.movement>=40&&h.started,a.sing>=150&&a.movement>=75&&works.length>=3&&works[0].settled===7,a.sing>=350&&a.movement>=175&&works.length>=10];h.pending=n<5&&ready[n]?n:null;}return s;}
function trained(s,a){init(s);const h=get(s,a.id);if(h)h.training++;}
function started(s,id,action){init(s);const h=get(s,id);if(h&&action.kind==='job'&&action.id==='radio')h.started=true;scan(s);}
function pending(s){return s.artists.map(a=>({artist:a,chapter:get(s,a.id)})).find(x=>x.chapter?.pending!=null)||null;}
function ensureIdea(s,id,career){const h=get(s,id),a=s.artists.find(a=>a.id===id);if(!h||!a||h.choices.length!==5)return null;let i=s.career.ideas.find(i=>i.id===h.ideaId);if(i&&!['shelved','withdrawn'].includes(i.status))return i;const n=career.name(s,'music');i={...n,id:'idea-'+(++s.career.serial),artistId:id,artistName:a.name,status:'pending',progress:0,revisions:0,fee:career.CONFIG.ideaFee,createdAt:s.lastTick,source:'music-chapter-1'};s.career.ideas.push(i);h.ideaId=i.id;return i;}
function resolve(s,id,n,key,career){scan(s);const h=get(s,id);if(!h||h.pending!==n||!choices[n]?.includes(key))return {ok:false,reason:'這段故事尚未解鎖，或已回應。'};h.choices.push({key,at:s.lastTick});h.pending=null;if(n===4)ensureIdea(s,id,career);scan(s);return {ok:true};}
function validate(s){const c=s.musicChapter;if(c===undefined)return;const fail=()=>{throw Error('音樂第一章紀錄損壞');};if(!c||c.version!==1||!c.artists||Array.isArray(c.artists))fail();const validView=(v,id)=>{const h=c.artists[v?.id];if(!h||(id&&v.id!==id)||!Number.isInteger(v.n)||v.n<0||v.n>4||v.n>h.choices.length||!Number.isInteger(v.line)||v.line<0||v.line>20)fail();};for(const [id,h] of Object.entries(c.artists)){if(!(s.customRegistry||[]).some(a=>a.id===id)||!h||!Array.isArray(h.choices)||h.choices.length>5||!Number.isSafeInteger(h.training)||h.training<0||typeof h.started!=='boolean'||!(h.pending===null||Number.isInteger(h.pending)&&h.pending===h.choices.length&&h.pending<5))fail();for(const [n,x] of h.choices.entries())if(!x||!choices[n].includes(x.key)||!Number.isFinite(x.at)||x.at<0||x.at>s.lastTick)fail();if(h.ideaId!==undefined&&!s.career.ideas.some(i=>i.id===h.ideaId&&i.artistId===id))fail();if(h.bookmark!==undefined)validView(h.bookmark,id);}if(c.reader!==null)validView(c.reader);}
return {choices,formal,get,init,scan,trained,started,pending,resolve,ensureIdea,validate};
});
