(function(r,f){const a=f();if(typeof module==='object'&&module.exports)module.exports=a;else r.StarPublicity=a;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const CONFIG=Object.freeze({shortPerDraw:30,longPerDraw:3,cooldownMs:300000,historyPageSize:30});
const CARDS=[
{id:'clip',title:'一段演出，忽然被大家看見',text:'觀眾上傳的片段受到討論，媒體想聽聽藝人的想法。你要怎麼回應這波關注？',choices:[{id:'thanks',label:'發文感謝觀眾',chance:1,good:6,bad:6,goodText:'真誠的感謝留下好印象。',badText:''},{id:'interview',label:'接受即席專訪',chance:.7,good:12,bad:-4,goodText:'自然的訪談讓更多人記住名字。',badText:'臨場回答被誤讀，討論有些失焦。'}]},
{id:'rumor',title:'一則尚未查證的貼文',text:'網路貼文把一段互動描述得有些尖銳，粉絲正在等待回應。',choices:[{id:'explain',label:'整理資訊，公開說明',chance:.7,good:8,bad:-6,goodText:'清楚的資訊化解了誤會。',badText:'說明太過急促，反而引來質疑。'},{id:'check',label:'先私下查證再簡短回覆',chance:1,good:3,bad:3,goodText:'謹慎回應讓討論逐漸平息。',badText:''},{id:'wait',label:'暫不回應，觀察發展',chance:.4,good:1,bad:-8,goodText:'話題自然冷卻，留下些微關注。',badText:'沉默被部分人解讀成默認。'}]},
{id:'backstage',title:'幕後玩笑引起不同解讀',text:'工作花絮中的一句玩笑被截成短片，有人覺得親切，也有人不太舒服。',choices:[{id:'context',label:'補上完整花絮',chance:.65,good:10,bad:-5,goodText:'完整脈絡讓觀眾看見團隊的默契。',badText:'補充片段仍沒消除所有人的疑慮。'},{id:'acknowledge',label:'誠懇致意，感謝提醒',chance:1,good:4,bad:4,goodText:'溫和的態度獲得理解。',badText:''}]},
{id:'headline',title:'訪談標題只留下半句話',text:'訪談報導的標題省略了前後文，有讀者誤會藝人是在批評合作夥伴。',choices:[{id:'headline_link',label:'免費附上完整訪談連結',chance:1,good:3,bad:3,goodText:'完整內容讓願意了解的人找到脈絡。',badText:''},{id:'headline_edit',label:'請公關整理逐字內容並聯繫編輯',chance:.7,good:8,bad:-4,goodText:'補充說明清楚，報導修正了標題。',badText:'反覆補充讓話題延燒，仍有人只看標題。'}]},
{id:'stage_slip',title:'演出的小失誤被放大討論',text:'現場一個節奏沒接好，觀眾把片段傳上網，團隊正在討論如何面對。',choices:[{id:'slip_ack',label:'免費承認失誤，說明會繼續練習',chance:1,good:2,bad:2,goodText:'平實的回應讓不少觀眾願意給予空間。',badText:''},{id:'slip_rehearse',label:'整理練習片段，公開後續調整',chance:.65,good:9,bad:-5,goodText:'具體的改進讓觀眾看見認真的態度。',badText:'過度強調練習被認為在為失誤辯解。'}]},
{id:'brief_change',title:'合作方臨時更改宣傳需求',text:'工作完成後，合作方提出與原討論不同的宣傳說法；雙方需要重新確認對外訊息。',choices:[{id:'brief_confirm',label:'免費書面確認已同意的內容',chance:1,good:3,bad:3,goodText:'釐清界線後，雙方順利使用一致說法。',badText:''},{id:'brief_meeting',label:'安排公關協調，重整宣傳說明',chance:.7,good:8,bad:-4,goodText:'協調找到了彼此都能接受的呈現方式。',badText:'協調過程拉長，部分訊息已先流出。'}]},
{id:'save_show',title:'臨場救場得到稱讚',text:'藝人協助接住現場的小空檔，觀眾稱讚反應自然，也有人想知道幕後過程。',choices:[{id:'save_credit',label:'免費發文感謝全體工作夥伴',chance:1,good:5,bad:5,goodText:'把功勞分享給團隊，留下穩重的印象。',badText:''},{id:'save_story',label:'製作幕後短訪，分享應變心得',chance:.7,good:10,bad:-3,goodText:'自然的分享讓更多人看見專業與默契。',badText:'剪輯太強調個人表現，引來搶功的誤解。'}]},
{id:'fan_support',title:'粉絲自發準備應援',text:'粉絲準備了小型應援，希望藝人看見心意，團隊也想提醒大家量力而為。',choices:[{id:'fan_thanks',label:'免費致謝，提醒不要勉強花費',chance:1,good:4,bad:4,goodText:'親切又體貼的回應讓支持者感到被尊重。',badText:''},{id:'fan_message',label:'錄製並整理一段正式感謝訊息',chance:.8,good:8,bad:-3,goodText:'用心的訊息讓這次應援留下溫暖回憶。',badText:'部分粉絲覺得訊息過於制式，熱情稍退。'}]},
{id:'credit_error',title:'宣傳圖誤植合作人員名字',text:'宣傳圖中的署名出現錯字，合作人員已私下提醒，需要處理更正。',choices:[{id:'credit_fix',label:'免費更正署名並誠懇致歉',chance:1,good:2,bad:2,goodText:'及時更正讓對方感受到尊重。',badText:''},{id:'credit_reissue',label:'重整宣傳素材，重新發布致謝',chance:.75,good:7,bad:-4,goodText:'完整致謝讓幕後夥伴也被更多人認識。',badText:'重新發布的解釋太多，焦點又回到疏漏。'}]},
{id:'schedule_notice',title:'公開活動時間傳出兩個版本',text:'不同宣傳頁面的活動時間不一致，有觀眾擔心白跑一趟，希望公司提供清楚指引。',choices:[{id:'schedule_pin',label:'免費置頂正確時間與更正說明',chance:1,good:3,bad:3,goodText:'明確指引讓多數觀眾順利安排時間。',badText:''},{id:'schedule_help',label:'安排專人協調各方公告與回覆',chance:.7,good:8,bad:-5,goodText:'一致的公告與耐心回覆贏得理解。',badText:'有些舊公告來不及修正，仍有觀眾感到失望。'}]}
];

const TERMS={thanks:{cost:0,goodFans:0,badFans:0},interview:{cost:80,goodFans:0,badFans:-12},explain:{cost:120,goodFans:0,badFans:-20},check:{cost:60,goodFans:0,badFans:0},wait:{cost:0,goodFans:0,badFans:-30},context:{cost:100,goodFans:0,badFans:-15},acknowledge:{cost:0,goodFans:0,badFans:0}};
Object.assign(TERMS,{headline_link:{cost:0,goodFans:0,badFans:0},headline_edit:{cost:80,goodFans:0,badFans:-12},slip_ack:{cost:0,goodFans:0,badFans:0},slip_rehearse:{cost:100,goodFans:0,badFans:-15},brief_confirm:{cost:0,goodFans:0,badFans:0},brief_meeting:{cost:120,goodFans:0,badFans:-15},save_credit:{cost:0,goodFans:0,badFans:0},save_story:{cost:80,goodFans:0,badFans:-10},fan_thanks:{cost:0,goodFans:0,badFans:0},fan_message:{cost:60,goodFans:0,badFans:-10},credit_fix:{cost:0,goodFans:0,badFans:0},credit_reissue:{cost:60,goodFans:0,badFans:-12},schedule_pin:{cost:0,goodFans:0,badFans:0},schedule_help:{cost:100,goodFans:0,badFans:-20}});
const terms=c=>({...TERMS[c.id]});
function init(s){s.publicity={policy:2,rng:((s.growthRng||123456789)^(Math.floor(s.startedAt)>>>0)^0x5075626c)>>>0,serial:0,shortCount:0,longCount:0,nextEligible:s.lastTick+CONFIG.cooldownMs,pending:null,history:[]};}
function migrate(s){const p=s.publicity;if(p.policy===2)return;p.policy=2;p.shortCount=Math.min(30,p.completedSinceDraw||0);p.longCount=0;delete p.completedSinceDraw;p.nextEligible=Math.max(p.nextEligible,s.lastTick+CONFIG.cooldownMs);if(p.pending)p.pending.terms=CARDS.find(c=>c.id===p.pending.cardId)?.choices.map(()=>({cost:0,goodFans:0,badFans:0}));}
function roll(p){p.rng=(Math.imul(p.rng,1664525)+1013904223)>>>0;return p.rng/4294967296;}
function completed(s,a,at,info={},offline=false){const p=s.publicity;if(p.pending)return null;const key=info.productionDays||info.kind==='special'?'longCount':'shortCount',cap=key==='longCount'?CONFIG.longPerDraw:CONFIG.shortPerDraw;p[key]=Math.min(cap,p[key]+1);if(offline||(p.shortCount<CONFIG.shortPerDraw&&p.longCount<CONFIG.longPerDraw)||at<p.nextEligible)return null;const pool=CARDS.filter(c=>c.id!==p.history[0]?.cardId),card=pool[Math.floor(roll(p)*pool.length)];p.pending={id:'publicity-'+(++p.serial),cardId:card.id,artistId:a.id,artistName:a.name,at,terms:card.choices.map(terms),outcomes:card.choices.map(c=>roll(p)<c.chance?'good':'bad')};p.shortCount=0;p.longCount=0;p.nextEligible=at+CONFIG.cooldownMs;return p.pending;}
function archive(s,entry){s.publicity.history.unshift(entry);s.publicity.pending=null;}
function expire(s,id){const p=s.publicity.pending;if(!p||p.artistId!==id)return false;archive(s,{...p,status:'expired',choiceId:null,delta:0,cashDelta:0,fanDelta:0,resolvedAt:s.lastTick,text:'藝人已離開公司，這張事件卡結束，不影響任何人。'});return true;}
function resolve(s,eventId,choiceId){const p=s.publicity.pending;if(!p||p.id!==eventId)return {ok:false,reason:'這張事件已處理，沒有重複結算。'};const a=s.artists.find(a=>a.id===p.artistId);if(!a){expire(s,p.artistId);return {ok:true,expired:true,delta:0,text:'藝人已不在公司，事件已結束。'};}const card=CARDS.find(c=>c.id===p.cardId),i=card.choices.findIndex(c=>c.id===choiceId);if(i<0)return {ok:false,reason:'請選擇卡片上的處理方式。'};const c=card.choices[i],t=p.terms[i];if(s.cash<t.cost)return {ok:false,reason:`資金不足，需要公關費 $${t.cost}；可選免費方式。`};const outcome=p.outcomes[i],planned=c[outcome],before=a.fame;a.fame=Math.max(0,Math.min(999,a.fame+planned));const delta=a.fame-before,cashDelta=0-t.cost,fanDelta=0-Math.min(s.fansByArtist[a.id]||0,-t[outcome+'Fans']),text=c[outcome+'Text'];s.cash+=cashDelta;if(fanDelta)s.fansByArtist[a.id]+=fanDelta;archive(s,{...p,status:'resolved',choiceId,delta,cashDelta,fanDelta,resolvedAt:s.lastTick,text});return {ok:true,delta,cashDelta,fanDelta,text,artistName:a.name};}
function validate(s){const p=s.publicity,num=n=>Number.isSafeInteger(n)&&n>=0;if(!p||p.policy!==2||!num(p.rng)||p.rng>4294967295||!num(p.serial)||!num(p.shortCount)||p.shortCount>30||!num(p.longCount)||p.longCount>3||!Number.isFinite(p.nextEligible)||p.nextEligible<0||!Array.isArray(p.history))throw Error('公關事件存檔損壞');const check=e=>{const c=CARDS.find(c=>c.id===e?.cardId);return !!c&&/^publicity-[1-9][0-9]*$/.test(e.id)&&Number(e.id.split('-')[1])<=p.serial&&typeof e.artistId==='string'&&typeof e.artistName==='string'&&Number.isFinite(e.at)&&e.at>=0&&Array.isArray(e.outcomes)&&e.outcomes.length===c.choices.length&&e.outcomes.every((x,i)=>['good','bad'].includes(x)&&(c.choices[i].chance!==1||x==='good'))&&(!e.terms||(Array.isArray(e.terms)&&e.terms.length===c.choices.length&&e.terms.every(t=>num(t.cost)&&t.cost<=120&&[t.goodFans,t.badFans].every(n=>Number.isInteger(n)&&n<=0&&n>=-30))));};if(p.pending&&(!check(p.pending)||!p.pending.terms))throw Error('待處理公關事件損壞');const ids=new Set(p.pending?[p.pending.id]:[]);for(const e of p.history){if(!check(e)||ids.has(e.id)||!['resolved','expired'].includes(e.status)||!Number.isInteger(e.delta)||e.delta < -8||e.delta>12||!Number.isFinite(e.resolvedAt)||typeof e.text!=='string'||!Number.isInteger(e.cashDelta??0)||(e.cashDelta??0)>0||(e.cashDelta??0)<-120||!Number.isInteger(e.fanDelta??0)||(e.fanDelta??0)>0||(e.fanDelta??0)<-30)throw Error('公關事件歷史損壞');ids.add(e.id);}}
return {CONFIG,CARDS,TERMS,init,migrate,completed,resolve,expire,validate};
});
