(()=>{
const G=StarGame,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),delta=n=>(n>=0?'+':'')+n;
 function result(r){return ['名氣 '+delta(r.delta||0),'公司資金 '+StarMoney.signed(r.cashDelta||0),'粉絲 '+delta(r.fanDelta||0)+' 人'].join(' · ');}
 function outcome(t,x,k){return '公司資金 '+StarMoney.signed((t[k+'Cash']||0)-t.cost)+' · 粉絲 '+delta(t[k+'Fans']||0)+' 人 · 名氣 '+delta(x[k]);}
 const opened=new Set();document.addEventListener('toggle',e=>{if(e.target.matches?.('.publicity-trigger-rules')){const id=e.target.dataset.rulesId;if(e.target.open)opened.add(id);else opened.delete(id);}},true);
function render(s){
 const pr=s.publicity,p=pr.pending,c=G.PUBLICITY.CARDS.find(c=>c.id===p?.cardId),a=s.artists.find(a=>a.id===p?.artistId),host=document.getElementById('publicity-content');
 document.querySelectorAll('[data-publicity-count]').forEach(el=>el.textContent=p?' · 1待處理':'');
 const alert=document.getElementById('publicity-alert');alert.hidden=!p;if(p)alert.textContent=`✦ ${p.artistName}遇到公關事件 · 等你決定`;
 host.innerHTML=`<details class="publicity-trigger-rules" data-rules-id="${p?.id||'none'}" ${opened.has(p?.id||'none')?'open':''}><summary>觸發規則</summary><p class="publicity-rule">短通告30件或長作品3件，獲得一次抽卡機會；首次及兩次抽卡至少間隔5現實分鐘。兩計數獨立，抽卡後一起歸零；重要邀約算長案。全公司最多1張待處理卡，待處理時不累積；離線只累積到門檻，不抽卡，回來完成工作才判定。助理不會代選。</p><p>目前短案 ${pr.shortCount}/30 · 長案 ${pr.longCount}/3 · 間隔尚餘 ${Math.max(0,Math.ceil((pr.nextEligible-s.lastTick)/1000))} 秒</p>
 </details>${p?`<article class="publicity-card"><small>PUBLICITY · #${pr.serial} · ${esc(p.artistName)}</small><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p>${a?`<p>個人名氣 <strong>${a.fame}/999</strong> · 粉絲 ${s.fansByArtist[a.id]||0} · 公司資金 $${s.cash}<br>${esc(G.currentActivityLabel(a))}</p><div class="publicity-choices">${c.choices.map((x,i)=>{const t=p.terms[i];return `<button data-publicity-id="${p.id}" data-publicity-choice="${x.id}" ${s.cash<t.cost?'disabled':''}><b>${esc(x.label)}</b><span>支出公關費：${StarMoney.format(t.cost)}${t.cost===0?'（免費）':s.cash<t.cost?'（資金不足）':''}<br>${x.chance===1?`穩健結果：${outcome(t,x,'good')}`:`成功 ${Math.round(x.chance*100)}%：${outcome(t,x,'good')}<br>失利 ${Math.round((1-x.chance)*100)}%：${outcome(t,x,'bad')}`}<br>以上資金為扣公關費後淨額；結果依機率判定。</span></button>`;}).join('')}</div>`:`<p>藝人已離開公司，事件不套用到其他人。</p><button data-publicity-id="${p.id}" data-publicity-choice="expired">結束事件</button>`}<small>公關費只扣一次；成功得到合作回饋，失利可能追加善後支出。資金與粉絲最低0，實際增減會列於紀錄。只調整當前粉絲，不改歷史作品曲線。抽卡時已固定結果與費用，刷新不重抽。</small></article>`:'<div class="publicity-empty"><h3>目前沒有待處理公關事件</h3><button data-panel="board">查看通告</button></div>'}
 <h3>處理紀錄</h3><div class="publicity-history">${pr.history.length?pr.history.slice(0,G.PUBLICITY.CONFIG.historyPageSize).map(h=>`<article><b>${esc(h.artistName)} · ${esc(G.PUBLICITY.CARDS.find(c=>c.id===h.cardId).title)}</b><p>${esc(h.text)}</p><strong class="${h.delta<0?'negative':'positive'}">${h.status==='expired'?'事件結束 · 無影響':`${result(h)}`}</strong></article>`).join(''):'<p>結果完整存檔，這裡顯示最近30次。</p>'}</div>`;
}
window.StarPublicityUI={render,result};
})();
