(() => {
 const G=StarGame,esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=x=>x.toLocaleString('zh-TW');
 const label=w=>({music:'音樂',drama:'戲劇',ad:'封面'}[w.kind]);
 let heatWork=null,heatPage=0,heatKey=null;
 function playbackLine(w,s){if(w.kind!=='music')return '';const r=s?.playbackRevenue?.works[w.id];return `<p class="playback-revenue" data-revenue-work="${w.id}">${!r||r.status==='legacy'?'舊案 · 不追溯播放收益':r.status==='settled'?`七天播放收益已結算：$${n(r.amount)} · 只入帳一次`:`播放收益待結算 · 七天總播放 × $0.003，無上限 · 預估 $${n(G.REVENUE.amount(w.stages.reduce((v,p)=>v+p.views,0)))}`}<br><small>僅升級後新接的正式音樂長案適用；不重乘藝人特長加成。</small></p>`;}
 let page=0;const PAGE_SIZE=12;
 function visibleWorks(s){page=Math.max(0,Math.min(page,Math.ceil(s.works.length/PAGE_SIZE)-1));const end=s.works.length-page*PAGE_SIZE;return s.works.slice(Math.max(0,end-PAGE_SIZE),end).reverse();}
 function timeLeft(w){const sec=Math.max(0,Math.ceil((w.stageMs*Math.min(7,w.settled+1)-w.ageMs)/1000));return `${Math.floor(sec/60)} 分 ${sec%60} 秒`;}
 function dailyChart(w,key,label,color){
  const actual=w.stages.slice(0,w.settled).map((p,i)=>({day:i+1,value:p[key]})),top=Math.max(2,Math.ceil(Math.max(0,...actual.map(p=>p.value))/2)*2),x=day=>54+(day-1)*56,y=value=>158-value/top*124;
  const fmt=v=>v>=10000?(v/10000).toFixed(1)+'萬':n(Math.round(v)),chartId=`chart-${w.id}-${key}`;
  return `<figure class="daily-chart" data-chart="${key}" data-work-id="${w.id}"><figcaption>${label}<small>當日數值 · 非累積</small></figcaption><svg viewBox="0 0 420 206" role="img" aria-labelledby="${chartId}"><title id="${chartId}">${label}，${w.settled?`已結算第 1 天至第 ${w.settled} 天`:'尚未結算'}；未到日期留白</title>${[0,.5,1].map(f=>`<line x1="54" x2="390" y1="${y(top*f)}" y2="${y(top*f)}" class="chart-grid"/><text x="45" y="${y(top*f)+4}" text-anchor="end" class="chart-axis">${fmt(top*f)}</text>`).join('')}${Array.from({length:7},(_,i)=>`<text x="${x(i+1)}" y="183" text-anchor="middle" class="chart-axis">第${i+1}天</text>`).join('')}${actual.length>=2?`<polyline class="daily-line" points="${actual.map(p=>`${x(p.day)},${y(p.value)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>`:''}${actual.map(p=>`<circle class="daily-point" data-day="${p.day}" data-value="${p.value}" cx="${x(p.day)}" cy="${y(p.value)}" r="4.5" fill="${color}"><title>第 ${p.day} 天：${label} ${n(p.value)}</title></circle>`).join('')}${actual.length?'':'<text x="222" y="96" text-anchor="middle" class="chart-empty">尚未結算，第一天結束後出現資料</text>'}</svg><small>${actual.length?`已結算 ${actual.length} 天；未到日期不畫點或補零。`:'七作品日共5分鐘，每天約43秒。'}</small></figure>`;
 }
 function workCard(w,s){const metric=w.kind==='music'?'播放數':'觀看',current=Math.min(7,w.settled+1),last=w.settled?w.stages[w.settled-1]:null,left=Math.max(0,Math.ceil((w.stageMs*current-w.ageMs)/60000));return `<article class="work-card" data-work="${w.id}"><div class="work-title"><div><small>${w.kind==='music'?'MUSIC · 音樂單曲':w.kind==='drama'?'DRAMA · 戲劇作品':'COVER · 封面作品'}</small><h3>${esc(StarDisplayCopy.workTitle(w))}</h3>${s?.workDescriptions?.[w.id]?`<p>${esc(StarDisplayCopy.description(s.workDescriptions[w.id].desc))}</p>`:""}<p>${esc(w.artistName)} · 推出 ${new Date(w.releasedAt).toLocaleString('zh-TW')}</p></div><span class="work-badge" data-work-clock="${w.id}">${w.settled===7?'七天宣傳已完成':`第 ${current} 天 / 共 7 天 · 剩 ${timeLeft(w)}`}</span></div><div class="work-meta"><span>品質 <b>${w.quality}/100</b></span><span>契合度 <b>${Math.round(w.fit*100)}%</b></span><span>${esc(w.curve)}</span><span>轉粉率 ${(w.conversion*100).toFixed(3)}%</span></div><div class="work-totals"><b>累積${metric} ${n(w.views)}</b><b>累積新增粉絲 ${n(w.fans)}</b><span>${last?`最近已結算第 ${w.settled} 天：${metric} ${n(last.views)} / 新粉 +${n(last.fans)}`:'尚未結算；下方為已鎖定預估'}</span></div>${playbackLine(w,s)}<div class="daily-charts">${dailyChart(w,'views','每日'+metric,'#587865')}${dailyChart(w,'fans','每日新增粉絲','#ae8750')}</div><details class="work-daily-details"><summary>每日明細（已入帳／尚未結算預估）</summary><small class="stage-scroll-hint">可向右滑動查看第 1 天～第 7 天 →</small><ol class="work-stages">${w.stages.map((p,i)=>`<li class="${i<w.settled?'settled':i===w.settled?'current':'future'}"><span>第 ${i+1} 天</span><b>${n(p.views)}</b><small>${metric}${i<w.settled?'已入帳':'預估'}</small><strong>+${n(p.fans)}</strong><small>新粉${i<w.settled?'已入帳':'預估'}</small></li>`).join('')}</ol></details></article>`;}
 window.StarWorksUI={
 setHeatWork(id){heatWork=Number(id);},setHeatPage(value){heatPage=Math.max(0,Math.floor(value)||0);heatWork=null;},
 renderHeat(s,demo){
   const host=document.getElementById('heat-page');if(!host||host.hidden)return;
   const key='starlane-heat-selection:'+s.startedAt;if(heatKey!==key){heatKey=key;heatWork=null;heatPage=0;try{const value=Number(sessionStorage.getItem(key));if(Number.isSafeInteger(value)&&value>0)heatWork=value;}catch{}}
   const index=s.works.findIndex(w=>w.id===heatWork);if(index>=0)heatPage=Math.floor((s.works.length-1-index)/PAGE_SIZE);
   heatPage=Math.max(0,Math.min(heatPage,Math.ceil(s.works.length/PAGE_SIZE)-1));
   const end=s.works.length-heatPage*PAGE_SIZE,rows=s.works.slice(Math.max(0,end-PAGE_SIZE),end).reverse();
   const work=rows.find(w=>w.id===heatWork)||rows[0];heatWork=work?.id??null;try{if(work)sessionStorage.setItem(heatKey,String(work.id));else sessionStorage.removeItem(heatKey);}catch{}
   host.innerHTML=`<div class="heat-heading"><button type="button" class="heat-return" data-home data-company-room="reception">回公司</button><span class="eyebrow">YOUR WORK · DAILY AUDIENCE</span><h1 tabindex="-1" id="heat-title">作品熱度</h1><p>戲劇與封面看觀看數，音樂看播放數；各作品分別結算新粉。七作品日共5分鐘，每天約43秒。</p></div>
   ${work?`<div class="heat-selection"><label for="heat-select">選擇作品 · 共 ${s.works.length} 件</label><select id="heat-select">${rows.map(w=>`<option value="${w.id}" ${w.id===work.id?'selected':''}>${label(w)} · ${esc(w.artistName)} · ${esc(StarDisplayCopy.workTitle(w))}</option>`).join('')}</select>${s.works.length>PAGE_SIZE?`<div class="work-pagination"><button data-heat-page="${heatPage-1}" ${heatPage===0?'disabled':''}>較新的作品</button><span>第 ${heatPage+1} / ${Math.ceil(s.works.length/PAGE_SIZE)} 頁</span><button data-heat-page="${heatPage+1}" ${end<=PAGE_SIZE?'disabled':''}>較早的作品</button></div>`:''}</div>${workCard(work,s).replaceAll('chart-'+work.id+'-', 'heat-chart-'+work.id+'-')}`:
   '<div class="works-empty"><h2>完成單曲、單元劇或封面後在此查看</h2><p>作品推出後，圖框會先顯示第一天倒數；每天結算後新增資料點。</p><button class="primary" data-panel="board" data-filter="ad">去挑選封面案 →</button><button data-panel="board" data-filter="music">去挑選單曲錄製 →</button><button data-panel="board" data-filter="drama">去挑選單元劇 →</button></div>'}
   ${demo?`<aside class="experience-controls"><b>獨立體驗 · 時間暫停</b><div class="work-actions"><button data-demo="ad">安排封面體驗（補齊門檻）</button><button data-demo="drama">安排單元劇體驗（補齊門檻）</button><button data-demo="music">安排單曲體驗（補齊出道門檻）</button><button data-demo="finish">完成目前行程</button><button data-demo="stage">快轉一天（約43秒）</button><button data-demo="offline">模擬離線 24 小時</button></div><small>僅影響體驗進度；單曲按鈕會補齊錄製門檻。正式遊戲沒有快轉。</small></aside>`:''}`;
 },
setPage(value){page=Math.max(0,Math.floor(value)||0);},tick(s){for(const w of [...visibleWorks(s),...s.works.filter(w=>w.id===heatWork)]){for(const el of document.querySelectorAll(`[data-work-clock="${w.id}"]`))el.textContent=w.settled===7?'七天宣傳已完成':`第 ${w.settled+1} 天 / 共 7 天 · 剩 ${timeLeft(w)}`;}},render(s,demo){
  visibleWorks(s);
  const q=G.expansionQuote(s),total=Object.values(s.fansByArtist).reduce((a,b)=>a+b,0),host=document.getElementById('works-content');
  host.innerHTML=`<div class="works-intro"><span class="eyebrow">AFTER THE SPOTLIGHT</span><h2>作品推出之後，故事繼續。</h2><p>每支作品從推出起計第 1 天到第 7 天，沒有全域行事曆。音樂作品僅由「穗光唱片 單曲錄製」完成時建立；歌藝訓練及現場演出不產生唱片，舊版歌曲無完整紀錄，不補造歷史曲線。七作品日共5分鐘，每天約43秒。藝人可以繼續工作，作品仍會累積觀看與粉絲。</p></div>
  <div class="works-summary"><div><small>已推出作品</small><strong>${s.works.length}<em> 件</em></strong></div><div><small>作品新增粉絲</small><strong>${n(total)}<em> 人</em></strong></div><div><small>公司名額</small><strong>${s.artists.length} / ${s.capacity}<em> 人</em></strong></div></div>
  ${demo?`<aside class="experience-controls"><b>七天體驗 · 獨立進度</b><p>時間暫停，以下按鈕只推進體驗存檔。正式資金、粉絲、名額不受影響。</p><div class="work-actions"><button data-demo="ad">安排封面體驗（補齊門檻）</button><button data-demo="drama">安排單元劇體驗（補齊門檻）</button><button data-demo="music">安排單曲體驗（補齊出道門檻）</button><button data-demo="finish">完成目前行程</button><button data-demo="stage">快轉一天（約43秒）</button><button data-demo="offline">模擬離線 24 小時</button><button data-demo="reset">重新體驗</button></div><small>先安排廣告 → 完成行程 → 按快轉逐日觀察；離線 24 小時仍只推進 4 小時。</small></aside>`:`<a class="experience-link" href="index.html?experience=seven" target="_blank" rel="noopener">開啟獨立「七天體驗」↗</a>`}
  <section class="expansion-box"><div><h3>${q?`擴充至 ${q.target} 人名額`:'三人工作室已就緒'}</h3><p>第二名額：公司知名度10＋$300（初版），不看品質；第三名額維持原廣告與粉絲條件。品質仍影響作品熱度。</p>${q?`<ul>${q.conditions.filter(c=>c.need).map(c=>`<li>${c.current>=c.need?'✓':'○'} ${c.label}：${c.current} / ${c.need}</li>`).join('')}</ul><p>擴充費 $${q.fee} · 目前資金 ${StarMoney.format(s.cash)}</p>`:'<p>已達目前上限；每批招募候選仍為兩位。</p>'}</div>${q?`<button data-expand="${q.target}" ${q.ok?'':'disabled'}>${q.ok?'支付 $'+q.fee+' 擴充':'條件尚未達成'}</button>`:''}</section>
  <details class="work-rules"><summary>七天、品質與轉粉怎麼算？</summary><p>七作品日共5分鐘，每天約43秒，共7個作品日、總長5分鐘；不必等待7個真實日。離線每次最多結算 4 小時，超出時間不偷跑；推出時間是紀錄，不是全域日曆。曲線和七天預估在推出時一次決定，重載不重抽，作品日結束才入帳。</p><p>廣告相關能力＝儀態×45%＋口才×35%＋自信×20%；音樂＝歌藝×70%＋自信×20%＋才智×10%；戲劇＝演技×70%＋口才×20%＋才智×10%；品質＝相關能力÷999×100，四捨五入（疲勞失誤時先乘 80%）。對應廣告／音樂專長契合度 100%，其他 85%。每日觀看／播放＝(2000＋品質×80)×契合度×(1＋推出時名氣÷999×50%)×曲線權重×0.85～1.15隨機係數，四捨五入；新增粉絲＝觀看×(0.4%＋品質×0.012%)×契合度，無條件捨去。</p><p>粉絲是本版新計數，不等於名氣；不回填、不加進 999 名氣，也不影響舊出道條件。解約後作品照常結算，粉絲保留在該藝人名下。觀看可重複曝光，粉絲為遊戲估計新增數，沒有跨作品受眾去重。曲線：首波話題／口碑升溫／細水長流；以上係數都是初版設計。</p></details>
  ${s.works.length>PAGE_SIZE?`<div class="work-pagination"><button data-work-page="${page-1}" ${page===0?'disabled':''}>較新的作品</button><span>第 ${page+1} / ${Math.ceil(s.works.length/PAGE_SIZE)} 頁 · 所有作品保留</span><button data-work-page="${page+1}" ${(page+1)*PAGE_SIZE>=s.works.length?'disabled':''}>較早的作品</button></div>`:''}<div class="work-list">${s.works.length?visibleWorks(s).map(w=>workCard(w,s)).join(''):'<div class="works-empty"><h3>第一件作品，等你完成製作。</h3><p>在通告佈告欄安排「穗光唱片 單曲錄製」、「週末單元劇」或「日常選物封面」，整件完成後作品才會出現在這裡。</p><button data-panel="board">挑選作品通告 →</button></div>'}</div>`;
 }};
})();
